import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Login from "../components/Login";
import Register from "../components/Register";
import { useState } from "react";
import ProtectedRoute from "../common/ProtectedRoute";

export default function Home() {
  const [type, setType] = useState("Login");
  return (
    <div className={styles.container}>
      <Head>
        <title>User Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/time_tracking.png" />
      </Head>
      {/* <ProtectedRoute> */}
      <div>
        {type === "Login" ? (
          <Login type={type} setType={setType} />
        ) : (
          <Register type={type} setType={setType} />
        )}
      </div>
      {/* </ProtectedRoute> */}
    </div>
  );
}
